"folder_path_example_where_python_is_installed\Python312\python.exe" "folder_path_example_where_wave_post_processing_script_is_saved\Python_Wave_PostProcessing\Wave_PostProcessingOrchestra.py"
pause
